### ISSUE TITLE
Feedback on March 25 draft of group update

### ISSUE THREAD

**Issue by manuelfs** [yipengsun/talks#2]
Focus on telling a story that Will, Zishuo, Hassan can follow. No need for many technical details, but need to explain what you are doing, why, and how. Here's feedback for the [3 slides](https://github.com/yipengsun/talks/releases/download/0.5.2/200326.pdf) you presented, but feel free to add more slides to fit all the information.

- Slide 2
  - [x] Explain that you are setting a new framework to produce ntuples based on Phoebe's. You are using a new release, but otherwise should be identical.
  - [x] Give a breakdown of the ratio between run 1 and 2 events, then correct for lumi, then correct for cross section
    - The luminosities for 2012 and 2016 are `1.98 ifb` and `1.62 ifb`, respectively
- Slide 3
  - [x] Explain that you use `Bd_D0Xmunu, D0=cocktail` MC to study the efficiency differences in Run 1 and 2 for each cut
  - [x] The rows of the  table should be descriptive: for instance, “StrippedBCands” → “Strip $D^0\mu$” or “SelMyB0” → “$D^{*+}\mu$ comb. with $m$, vtx cuts”
  - [x] Move `Step 2 cuts` to the end of the table and separate each cut into a row
  - [x] Uncertainties should only have 2 digits of precision
  - [x] Explain the results of the table a bit
    - Stripping 33% more efficient in Run 2 due to looser cuts (despite including HLT), can give an example. 
    - HLT more efficient due to new paths
    - Factor of 1.67 does not match the 2.5 that we saw in data
- Slide 4
  - [x] Bullet 1 explained in Slide 2 and bullet 2 in Slide 3
  - [x] Results for MC seem largely as expected, but they do not match what we saw in data
    - Will study possible differences in data with another cutflow
- Backup
  - [x] Add details of differences between Run 1 and 2 stripping
  - [x] Add details of the cuts in `SelMyD0`, `SelMyDst`, `SelMyB0`, `SelMyRefitB02DstMu`
  - [x] Add names and any detail you may have of the trigger lines (L0, HLT1, HLT2) in runs 1 and 2

**Comment by yipengsun** [comment]
@manuelfs I've updated the talk (except for the backup slides). Can you take another look?

**Comment by yipengsun** [comment]
Also, I think I'll postpone updating the backup slides to the actual SL WG talk.

**Comment by manuelfs** [comment]
Very nice slides, now the story flows quite well. Remember to upload them to indico before the meeting
https://indico.cern.ch/event/900394/

Minor comments
2: "based *on* Phoebe's"
2: Add DaVinci releases
2: "5 times more events in Run 2 than in Run 1 per ifb"
3: Subbullet after shape: "Dominated by B->D*munu events, not background"
3: What is the actual number of events in each distribution? Use those numbers for the ratio
3: "Run 2 selection is 2.5 times more efficient, but expected ~1.7"
4: Love the new horizontal lines!
6: Add "Next steps: implementation of FF/PID/other weights, MC/data comparisons, preparation of MC request"
Backup: Add at least a screenshot of my issue comparing stripping cuts (although it is very nice that you picked a few in slide 5). 

Thanks!
